# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'PTGGroMoreDemo' do
  
  post_install do |installer|
        installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
        end
      end
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Ads-CN', '6.9.1.2', :subspecs => ['CSJMediation']
  pod 'PTGAdFramework', '~> 2.2.94'
  pod 'PTGGroMoreAdapter','2.2.94.0'
  pod 'YYCategories'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'CocoaDebug'
  # Pods for PTGGroMoreDemo

  
end
